services:
  - type: web
    name: unitopuz
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node start.mjs
    envVars:
      - key: NITRO_PRESET
        value: node-server
      - key: NODE_ENV
        value: production
