services:
  - type: web
    name: unitopuz
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: NITRO_PRESET
        value: node-server
      - key: NODE_ENV
        value: production
