/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as TestsIndexRouteImport } from './routes/tests.index'
import { Route as UniversitiesIndexRouteImport } from './routes/universities.index'
import { Route as UniversitiesIdRouteImport } from './routes/universities.$id'
import { Route as TestsSubjectIndexRouteImport } from './routes/tests.$subject.index'
import { Route as TestsSubjectRunRouteImport } from './routes/tests.$subject.run'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesIndexRoute = UniversitiesIndexRouteImport.update({
  id: '/universities/',
  path: '/universities/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesIdRoute = UniversitiesIdRouteImport.update({
  id: '/universities/$id',
  path: '/universities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsSubjectIndexRoute = TestsSubjectIndexRouteImport.update({
  id: '/tests/$subject/',
  path: '/tests/$subject/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsSubjectRunRoute = TestsSubjectRunRouteImport.update({
  id: '/tests/$subject/run',
  path: '/tests/$subject/run',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/materials': typeof MaterialsRoute
  '/programs': typeof ProgramsRoute
  '/results': typeof ResultsRoute
  '/universities/$id': typeof UniversitiesIdRoute
  '/tests/': typeof TestsIndexRoute
  '/universities/': typeof UniversitiesIndexRoute
  '/tests/$subject/run': typeof TestsSubjectRunRoute
  '/tests/$subject/': typeof TestsSubjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/materials': typeof MaterialsRoute
  '/programs': typeof ProgramsRoute
  '/results': typeof ResultsRoute
  '/universities/$id': typeof UniversitiesIdRoute
  '/tests': typeof TestsIndexRoute
  '/universities': typeof UniversitiesIndexRoute
  '/tests/$subject/run': typeof TestsSubjectRunRoute
  '/tests/$subject': typeof TestsSubjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/materials': typeof MaterialsRoute
  '/programs': typeof ProgramsRoute
  '/results': typeof ResultsRoute
  '/universities/$id': typeof UniversitiesIdRoute
  '/tests/': typeof TestsIndexRoute
  '/universities/': typeof UniversitiesIndexRoute
  '/tests/$subject/run': typeof TestsSubjectRunRoute
  '/tests/$subject/': typeof TestsSubjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/materials'
    | '/programs'
    | '/results'
    | '/universities/$id'
    | '/tests/'
    | '/universities/'
    | '/tests/$subject/run'
    | '/tests/$subject/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/materials'
    | '/programs'
    | '/results'
    | '/universities/$id'
    | '/tests'
    | '/universities'
    | '/tests/$subject/run'
    | '/tests/$subject'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/materials'
    | '/programs'
    | '/results'
    | '/universities/$id'
    | '/tests/'
    | '/universities/'
    | '/tests/$subject/run'
    | '/tests/$subject/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  MaterialsRoute: typeof MaterialsRoute
  ProgramsRoute: typeof ProgramsRoute
  ResultsRoute: typeof ResultsRoute
  UniversitiesIdRoute: typeof UniversitiesIdRoute
  TestsIndexRoute: typeof TestsIndexRoute
  UniversitiesIndexRoute: typeof UniversitiesIndexRoute
  TestsSubjectRunRoute: typeof TestsSubjectRunRoute
  TestsSubjectIndexRoute: typeof TestsSubjectIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/': {
      id: '/universities/'
      path: '/universities'
      fullPath: '/universities/'
      preLoaderRoute: typeof UniversitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/$id': {
      id: '/universities/$id'
      path: '/universities/$id'
      fullPath: '/universities/$id'
      preLoaderRoute: typeof UniversitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$subject/': {
      id: '/tests/$subject/'
      path: '/tests/$subject'
      fullPath: '/tests/$subject/'
      preLoaderRoute: typeof TestsSubjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$subject/run': {
      id: '/tests/$subject/run'
      path: '/tests/$subject/run'
      fullPath: '/tests/$subject/run'
      preLoaderRoute: typeof TestsSubjectRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  MaterialsRoute: MaterialsRoute,
  ProgramsRoute: ProgramsRoute,
  ResultsRoute: ResultsRoute,
  UniversitiesIdRoute: UniversitiesIdRoute,
  TestsIndexRoute: TestsIndexRoute,
  UniversitiesIndexRoute: UniversitiesIndexRoute,
  TestsSubjectRunRoute: TestsSubjectRunRoute,
  TestsSubjectIndexRoute: TestsSubjectIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
